version: "3"
services:
  python:
    build: ./django_apps
    volumes:
      - ./django_apps:/app
    ports:
      - "8081:80"
    user: root
    command: ["./wait-for-postgres.sh", "postgres", "python", "manage.py", "runserver", "0:80"]
    networks:
      - webnet

  postgres:
    build: ./postgres
    volumes:
      - /root/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - webnet

networks:
  webnet:


