version: "3"
services:
  python:
    build: apps
    volumes:
      - ./apps:/app
    ports:
      - "8081:80"
    user: root
    entrypoint: ["./wait-for-postgres.sh", "postgres", "python", "manage.py", "runserver", "0:80"]
    networks:
      - webnet

  postgres:
    build: ./docker/postgres
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - webnet

networks:
  webnet:


