# Generated by Django 2.1.7 on 2019-04-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190313_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='acting_in', through='core.Role', to='core.Person'),
        ),
    ]
