# Generated by Django 2.1.7 on 2019-03-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20190306_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
